### ISSUE TITLE
The ¨Quiero apuntarme¨ button does not appear centered on mobile.

### ISSUE THREAD

**Issue by seniorglez** [NanyThery/tt-web-react#26]
The ¨Quiero apuntarme¨ button does not appear centered on mobile.

This is the reproduction of the bug using firefox debugging tools.

![bug](https://user-images.githubusercontent.com/44611837/161447277-621cb375-411c-4d2d-b540-23c8144a9d13.png)

**Comment by NanyThery** [comment]
Fixed with last PR - Thnx
