### ISSUE TITLE
Create Staff page

### ISSUE THREAD

**Issue by 4lejandrito** [NanyThery/tt-web-react#3]
- [X] Header
- [X] Members list
- [X] "You" purple card
- [X] Modal with extra info
- [X] Quiero colaborar footer
- [x] Hover effect with gifs
- [x] People from 2020
- [x] Responsive design
- [x] Quiero colaborar buttons
- [x] Add all the pending gifs (mp4s)
- [x] Review with Yoli

**Comment by NanyThery** [comment]
I added the buttons in the last forms PR update 👍🏼
