### ISSUE TITLE
Revisar permisos para enviar PR

### ISSUE THREAD

**Issue by beajmnz** [NanyThery/tt-web-react#30]
(No perder mucho tiempo con ello, que es muy probable que no sea fallo del repo sino inutilidad de servidora)

**Comment by NanyThery** [comment]
Bea, no deja hacer PR si se hace desde un fork. Para poder subir PRs hay que descargar este repo directamente. :D

**Comment by beajmnz** [comment]
¿no se pueden hacer PRs desde la propia web entonces? el fork se empeñó en hacerlo Github, yo no quería... :-(
