### ISSUE TITLE
Wrong redirect 

### ISSUE THREAD

**Issue by aguadotzn** [NanyThery/tt-web-react#53]
Google is indexing previous web (https://www.teacht3ch.com/index.html). We should redirect into new index

<img width="1191" alt="Screenshot 2022-05-05 at 15 05 30" src="https://user-images.githubusercontent.com/22575055/166929030-1ca33d9e-812e-45d3-a737-729ac5c8259a.png">

**Comment by seniorglez** [comment]
Probably google has not crawl through the new website and therefore points to the wrong address. This should be solved in about a week when google preforms another crawl. I think that adding a go to home button to the 404 error page will solve our problem for now.

I`m attaching a screenshot of the issue just for the record.
![image](https://user-images.githubusercontent.com/44611837/166970705-f40f6c53-368e-4465-971a-5b7c2761b5c4.png)

**Comment by seniorglez** [comment]
I was checking if google is no longer pointing to the old url and the problem seems to be fixed already. Therefore I am closing this issue.
